/* eslint-disable */
// WARNING: Do not edit this file

const ebconfig = {
  "integration": "project-Star_Wars_Capstone-EMrcejkaIJW0EiodNBmYsHr0qhfcGXeR",
  "version": "2020-11-20"
}

export default ebconfig;